package demox;

public class Excep1 {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		
		int ar[]=new int[5];
		try
		{
			ar[0]=23;
			ar[1]=24;
			ar[2]=25;
			ar[3]=26;
			ar[4]=27;
			ar[5]=28;
		}
		catch(Exception e)
		{
			e.printStackTrace();
		}
		System.out.println("The elements of array are");
		for(int i:ar)
		{
			System.out.println(i);
		}
		
	}

}
/*Exception Handling

Exception: abnormal condition which disrupts the normal flow of program execution.

Error : are irrecoverable

Exception : 
1)Unchecked exception : Runtime Exception
2)Checked exception : Compile time Exception
 *
 * Unchecked Exception : Whenever we are generating any logical error 
 * Checked Exception : whenever we are working outside the environment of java 
 * 
 * file handling
 * database connectivity
 * 
 * java.lang
 * 
 * Throwable 
 * ->Exception 								Error
 * -->IOException							->VirtualMachineError
 * -->SQLException							->OutOfMemoryError
 * -->ClassNotFoundException				->StackOverflowError
 * -->FileNotFoundException
 * 
 * -->RuntimeException
 * ---->ArithmeticException
 * ---->NullPointerException
 * ---->NumberFormatException
 * 
 * ---->IndexOutOfBoundsException
 * ------>StringIndexOutOfBoundsException
 * ------>ArrayIndexOutOfBoundsException
 * 
 * 
 * difference between final, finally and finalize()
 * 
 * 
 * try : try is a block  in which we should place the exception code.try must be followed by a catch
 * or finally block
 * 
 * catch : block is used to handle the exception generated by the try.catch must be preceded by try.
 * catch cannot be made individually.
 * 
 * finally : block which is used to execute the code irrespective of exception.
 * 
 * try-catch
 * try-finally
 * try-catch-finally
 * 
 * 15 minutes : 
 * DefaultExceptionHandler 
 * JVM 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 *
 * 
 * 
 */
